"""
Build-time web asset pipeline.

Reads every file under web/, strips the dev-only mock block, gzips at maximum
compression, and emits include/generated/web_assets.h as a PROGMEM table.

Wire it up in platformio.ini:

    extra_scripts = pre:tools/gen_web_assets.py
    custom_web_src = web
    custom_web_out = include/generated/web_assets.h
    custom_web_max_bytes = 24576
"""

import gzip
import hashlib
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

Import("env")  # noqa: F821  (injected by SCons)

SRC_DIR = env.GetProjectOption("custom_web_src", "web")
OUT_FILE = env.GetProjectOption("custom_web_out", "include/generated/web_assets.h")
MAX_BYTES = int(env.GetProjectOption("custom_web_max_bytes", "24576"))

MIME = {
    ".html": "text/html",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".png": "image/png",
    ".txt": "text/plain",
}

# Everything between these markers is stripped from shipped assets.
MOCK_RE = re.compile(
    r"/\*\s*-*\s*mock backend.*?\*/.*?(?=\n\s*</script>)",
    re.IGNORECASE | re.DOTALL,
)

TEXT_EXT = {".html", ".css", ".js", ".json", ".svg", ".txt"}


def log(msg):
    print("[web] " + msg)


def firmware_version():
    try:
        v = subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty"],
            stderr=subprocess.DEVNULL,
        )
        return v.decode().strip()
    except Exception:
        return "dev"


def route_for(rel):
    route = "/" + rel.replace(os.sep, "/")
    return "/" if route == "/index.html" else route


def collect():
    assets = []
    if not os.path.isdir(SRC_DIR):
        log("source directory '%s' not found" % SRC_DIR)
        return assets

    for root, _, files in os.walk(SRC_DIR):
        for name in sorted(files):
            if name.startswith("."):
                continue
            path = os.path.join(root, name)
            rel = os.path.relpath(path, SRC_DIR)
            ext = os.path.splitext(name)[1].lower()

            raw = open(path, "rb").read()

            if ext in TEXT_EXT:
                text = raw.decode("utf-8")
                stripped, n = MOCK_RE.subn("", text)
                if n:
                    log("%s: stripped %d dev block(s)" % (rel, n))
                raw = stripped.encode("utf-8")

            # mtime=0 so identical input always produces identical output,
            # otherwise every build looks changed and nothing is incremental.
            gz = gzip.compress(raw, compresslevel=9, mtime=0)
            etag = hashlib.sha1(raw).hexdigest()[:16]

            assets.append(
                {
                    "route": route_for(rel),
                    "symbol": re.sub(r"[^A-Za-z0-9]", "_", rel).upper(),
                    "mime": MIME.get(ext, "application/octet-stream"),
                    "gz": gz,
                    "raw_len": len(raw),
                    "etag": etag,
                }
            )
    return assets


def emit(assets, version, stamp):
    out = []
    w = out.append

    w("// Generated by tools/gen_web_assets.py. Do not edit.")
    w("#ifndef WEB_ASSETS_H")
    w("#define WEB_ASSETS_H")
    w("#include <Arduino.h>")
    w("")
    w('#define FIRMWARE_VERSION "%s"' % version)
    w('#define FIRMWARE_BUILD_STAMP "%s"' % stamp)
    w("")

    for a in assets:
        w("// %s  %d -> %d bytes" % (a["route"], a["raw_len"], len(a["gz"])))
        w("alignas(4) static const uint8_t %s_GZ[] PROGMEM = {" % a["symbol"])
        for i in range(0, len(a["gz"]), 16):
            chunk = a["gz"][i : i + 16]
            w("  " + ",".join("0x%02x" % b for b in chunk) + ",")
        w("};")
        w("")

    w("struct WebAsset {")
    w("  const char*    path;")
    w("  const char*    contentType;")
    w("  const uint8_t* data;")
    w("  size_t         len;")
    w("  const char*    etag;")
    w("};")
    w("")
    w("static const WebAsset WEB_ASSETS[] PROGMEM = {")
    for a in assets:
        w(
            '  { "%s", "%s", %s_GZ, %d, "%s" },'
            % (a["route"], a["mime"], a["symbol"], len(a["gz"]), a["etag"])
        )
    w("};")
    w("static const size_t WEB_ASSET_COUNT = %d;" % len(assets))
    w("#endif // WEB_ASSETS_H")
    w("")
    return "\n".join(out)


def main():
    assets = collect()
    total = sum(len(a["gz"]) for a in assets)

    for a in assets:
        log(
            "%-24s %6d -> %5d  (%s)"
            % (a["route"], a["raw_len"], len(a["gz"]), a["etag"])
        )

    if total > MAX_BYTES:
        log("FAIL: assets total %d bytes, budget is %d" % (total, MAX_BYTES))
        env.Exit(1)

    version = firmware_version()
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    body = emit(assets, version, stamp)

    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)

    # Compare ignoring the stamp line, so an unchanged web/ does not
    # force a rebuild of every translation unit that includes the header.
    def without_stamp(t):
        return "\n".join(
            l for l in t.splitlines() if "FIRMWARE_BUILD_STAMP" not in l
        )

    if os.path.exists(OUT_FILE):
        old = open(OUT_FILE).read()
        if without_stamp(old) == without_stamp(body):
            log("unchanged (%d bytes total, %d%% of budget)"
                % (total, round(100 * total / MAX_BYTES)))
            return

    open(OUT_FILE, "w").write(body)
    log("wrote %s  (%d bytes total, %d%% of budget)"
        % (OUT_FILE, total, round(100 * total / MAX_BYTES)))


main()
